name: "Pull Request CI"
on:
  - pull_request
jobs:
  build-released:
    name: JVM build - released Quarkus
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK {{ matrix.java }}
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: openjdk${{ matrix.java }}
      - name: Build with Maven
        run: mvn -fae -V -B -s .github/mvn-settings.xml clean test -Dinclude.serverless -Dinclude.datagrid -Dvalidate-format
      - name: Zip Artifacts
        run: |
          zip -R artifacts-jvm${{ matrix.java }}.zip 'surefire-reports/*'
      - uses: actions/upload-artifact@v1
        with:
          name: ci-artifacts
          path: artifacts-jvm${{ matrix.java }}.zip
  build-released-native:
    name: Native build - released Quarkus
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK {{ matrix.java }}
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: openjdk${{ matrix.java }}
      - name: Build with Maven
        run: |
          mvn -fae -V -B clean install -s .github/mvn-settings.xml -DskipTests -DskipITs -pl 'app-metadata/deployment,app-metadata/runtime,common,http/http-minimum' -Dquarkus.profile=native -Dquarkus.native.container-runtime=docker
  build-main:
    name: JVM build - Quarkus main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK {{ matrix.java }}
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: openjdk${{ matrix.java }}
      - name: Build Quarkus main
        run: git clone https://github.com/quarkusio/quarkus.git && cd quarkus && mvn -B -s .github/mvn-settings.xml clean install -DskipTests -DskipITs -DskipDocs
      - name: Build with Maven
        run: mvn -fae -V -B clean test -s .github/mvn-settings.xml -Dquarkus-core-only -Dinclude.serverless -Dinclude.datagrid
      - name: Zip Artifacts
        run: |
          zip -R artifacts-jvm${{ matrix.java }}.zip 'surefire-reports/*'
      - uses: actions/upload-artifact@v1
        with:
          name: ci-artifacts
          path: artifacts-jvm${{ matrix.java }}.zip
